import { ImageURISource } from 'react-native';

const Icons: { [key: string]: ImageURISource | number } = {
  missing_blue: require('../assets/icons/missing_blue.png'),

  ambulance_blue: require('../assets/icons/vehicles/ambulance/ambulance_blue.png'),
  ambulance_green: require('../assets/icons/vehicles/ambulance/ambulance_green.png'),
  ambulance_grey: require('../assets/icons/vehicles/ambulance/ambulance_grey.png'),
  ambulance_orange: require('../assets/icons/vehicles/ambulance/ambulance_orange.png'),

  boat_blue: require('../assets/icons/vehicles/boat/boat_blue.png'),
  boat_green: require('../assets/icons/vehicles/boat/boat_green.png'),
  boat_grey: require('../assets/icons/vehicles/boat/boat_grey.png'),
  boat_orange: require('../assets/icons/vehicles/boat/boat_orange.png'),

  bulldozer_blue: require('../assets/icons/vehicles/bulldozer/bulldozer_blue.png'),
  bulldozer_green: require('../assets/icons/vehicles/bulldozer/bulldozer_green.png'),
  bulldozer_grey: require('../assets/icons/vehicles/bulldozer/bulldozer_grey.png'),
  bulldozer_orange: require('../assets/icons/vehicles/bulldozer/bulldozer_orange.png'),

  bus_blue: require('../assets/icons/vehicles/bus/bus_blue.png'),
  bus_green: require('../assets/icons/vehicles/bus/bus_green.png'),
  bus_grey: require('../assets/icons/vehicles/bus/bus_grey.png'),
  bus_orange: require('../assets/icons/vehicles/bus/bus_orange.png'),

  bus_mini_blue: require('../assets/icons/vehicles/bus_mini/bus_mini_blue.png'),
  bus_mini_green: require('../assets/icons/vehicles/bus_mini/bus_mini_green.png'),
  bus_mini_grey: require('../assets/icons/vehicles/bus_mini/bus_mini_grey.png'),
  bus_mini_orange: require('../assets/icons/vehicles/bus_mini/bus_mini_orange.png'),

  car_blue: require('../assets/icons/vehicles/car/car_blue.png'),
  car_green: require('../assets/icons/vehicles/car/car_green.png'),
  car_grey: require('../assets/icons/vehicles/car/car_grey.png'),
  car_orange: require('../assets/icons/vehicles/car/car_orange.png'),

  crane_truck_blue: require('../assets/icons/vehicles/crane_truck/crane_truck_blue.png'),
  crane_truck_green: require('../assets/icons/vehicles/crane_truck/crane_truck_green.png'),
  crane_truck_grey: require('../assets/icons/vehicles/crane_truck/crane_truck_grey.png'),
  crane_truck_orange: require('../assets/icons/vehicles/crane_truck/crane_truck_orange.png'),

  dump_truck_blue: require('../assets/icons/vehicles/dump_truck/dump_truck_blue.png'),
  dump_truck_green: require('../assets/icons/vehicles/dump_truck/dump_truck_green.png'),
  dump_truck_grey: require('../assets/icons/vehicles/dump_truck/dump_truck_grey.png'),
  dump_truck_orange: require('../assets/icons/vehicles/dump_truck/dump_truck_orange.png'),

  garbage_truck_blue: require('../assets/icons/vehicles/garbage_truck/garbage_truck_blue.png'),
  garbage_truck_green: require('../assets/icons/vehicles/garbage_truck/garbage_truck_green.png'),
  garbage_truck_grey: require('../assets/icons/vehicles/garbage_truck/garbage_truck_grey.png'),
  garbage_truck_orange: require('../assets/icons/vehicles/garbage_truck/garbage_truck_orange.png'),

  generator_blue: require('../assets/icons/vehicles/generator/generator_blue.png'),
  generator_green: require('../assets/icons/vehicles/generator/generator_green.png'),
  generator_grey: require('../assets/icons/vehicles/generator/generator_grey.png'),
  generator_orange: require('../assets/icons/vehicles/generator/generator_orange.png'),

  mix_truck_blue: require('../assets/icons/vehicles/mix_truck/mix_truck_blue.png'),
  mix_truck_green: require('../assets/icons/vehicles/mix_truck/mix_truck_green.png'),
  mix_truck_grey: require('../assets/icons/vehicles/mix_truck/mix_truck_grey.png'),
  mix_truck_orange: require('../assets/icons/vehicles/mix_truck/mix_truck_orange.png'),

  motorcycle_blue: require('../assets/icons/vehicles/motorcycle/motorcycle_blue.png'),
  motorcycle_green: require('../assets/icons/vehicles/motorcycle/motorcycle_green.png'),
  motorcycle_grey: require('../assets/icons/vehicles/motorcycle/motorcycle_grey.png'),
  motorcycle_orange: require('../assets/icons/vehicles/motorcycle/motorcycle_orange.png'),

  pickup_blue: require('../assets/icons/vehicles/pickup/pickup_blue.png'),
  pickup_green: require('../assets/icons/vehicles/pickup/pickup_green.png'),
  pickup_grey: require('../assets/icons/vehicles/pickup/pickup_grey.png'),
  pickup_orange: require('../assets/icons/vehicles/pickup/pickup_orange.png'),

  pump_truck_blue: require('../assets/icons/vehicles/pump_truck/pump_truck_blue.png'),
  pump_truck_green: require('../assets/icons/vehicles/pump_truck/pump_truck_green.png'),
  pump_truck_grey: require('../assets/icons/vehicles/pump_truck/pump_truck_grey.png'),
  pump_truck_orange: require('../assets/icons/vehicles/pump_truck/pump_truck_orange.png'),

  scooter_blue: require('../assets/icons/vehicles/scooter/scooter_blue.png'),
  scooter_green: require('../assets/icons/vehicles/scooter/scooter_green.png'),
  scooter_grey: require('../assets/icons/vehicles/scooter/scooter_grey.png'),
  scooter_orange: require('../assets/icons/vehicles/scooter/scooter_orange.png'),

  six_wheel_blue: require('../assets/icons/vehicles/six_wheel/six_wheel_blue.png'),
  six_wheel_green: require('../assets/icons/vehicles/six_wheel/six_wheel_green.png'),
  six_wheel_grey: require('../assets/icons/vehicles/six_wheel/six_wheel_grey.png'),
  six_wheel_orange: require('../assets/icons/vehicles/six_wheel/six_wheel_orange.png'),

  tanker_blue: require('../assets/icons/vehicles/tanker/tanker_blue.png'),
  tanker_green: require('../assets/icons/vehicles/tanker/tanker_green.png'),
  tanker_grey: require('../assets/icons/vehicles/tanker/tanker_grey.png'),
  tanker_orange: require('../assets/icons/vehicles/tanker/tanker_orange.png'),

  trailer_truck_blue: require('../assets/icons/vehicles/trailer_truck/trailer_truck_blue.png'),
  trailer_truck_green: require('../assets/icons/vehicles/trailer_truck/trailer_truck_green.png'),
  trailer_truck_grey: require('../assets/icons/vehicles/trailer_truck/trailer_truck_grey.png'),
  trailer_truck_orange: require('../assets/icons/vehicles/trailer_truck/trailer_truck_orange.png'),

  truck_blue: require('../assets/icons/vehicles/truck/truck_blue.png'),
  truck_green: require('../assets/icons/vehicles/truck/truck_green.png'),
  truck_grey: require('../assets/icons/vehicles/truck/truck_grey.png'),
  truck_orange: require('../assets/icons/vehicles/truck/truck_orange.png'),

  vehicle_front_orange: require('../assets/icons/vehicles/vehicle_front_orange.png'),
  vehicle_front_green: require('../assets/icons/vehicles/vehicle_front_green.png'),
  vehicle_front_grey: require('../assets/icons/vehicles/vehicle_front_grey.png'),
  vehicle_front_white: require('../assets/icons/vehicles/vehicle_front_white.png'),

  calender_daily_blue: require('../assets/icons/calender_daily_blue.png'),
  calender_general_grey: require('../assets/icons/calender_general_grey.png'),
  calender_general_time_grey: require('../assets/icons/calender_general_time_grey.png'),
  calender_general_white: require('../assets/icons/calender_general_white.png'),
  calender_monthly_blue: require('../assets/icons/calender_monthly_blue.png'),
  calender_weekly_blue: require('../assets/icons/calender_weekly_blue.png'),

  call_blue: require('../assets/icons/call_blue.png'),
  call_white: require('../assets/icons/call_white.png'),

  caret_up_blue: require('../assets/icons/caret/caret_up_blue.png'),
  caret_down_blue: require('../assets/icons/caret/caret_down_blue.png'),
  caret_right_blue: require('../assets/icons/caret/caret_right_blue.png'),
  caret_left_blue: require('../assets/icons/caret/caret_left_blue.png'),

  caret_up_white: require('../assets/icons/caret/caret_up_white.png'),
  caret_down_white: require('../assets/icons/caret/caret_down_white.png'),
  caret_right_white: require('../assets/icons/caret/caret_right_white.png'),
  caret_left_white: require('../assets/icons/caret/caret_left_white.png'),

  caret_up_grey: require('../assets/icons/caret/caret_up_grey.png'),
  caret_down_grey: require('../assets/icons/caret/caret_down_grey.png'),
  caret_right_grey: require('../assets/icons/caret/caret_right_grey.png'),
  caret_left_grey: require('../assets/icons/caret/caret_left_grey.png'),

  caret_up_blue_second: require('../assets/icons/caret/caret_up_blue2.png'),
  caret_down_blue_second: require('../assets/icons/caret/caret_down_blue2.png'),
  caret_right_blue_second: require('../assets/icons/caret/caret_right_blue2.png'),
  caret_left_blue_second: require('../assets/icons/caret/caret_left_blue2.png'),

  clock_grey: require('../assets/icons/clock_grey.png'),
  cross_white: require('../assets/icons/cross_white.png'),
  dashboard_white: require('../assets/icons/dashboard_white.png'),
  driver_grey: require('../assets/icons/driver_grey.png'),
  driver_white: require('../assets/icons/driver_white.png'),
  driver_management_white: require('../assets/icons/driver_management_white.png'),
  dropdown_check_blue: require('../assets/icons/dropdown_check_blue.png'),
  edit_blue: require('../assets/icons/edit_blue.png'),
  filter_white: require('../assets/icons/filter_white.png'),
  fleet_utilization_blue: require('../assets/icons/fleet_utilization_blue.png'),
  geofence_blue: require('../assets/icons/geofence_blue.png'),
  geofence_entry_grey: require('../assets/icons/geofence_entry_grey.png'),
  geofence_exit_grey: require('../assets/icons/geofence_exit_grey.png'),
  geofence_trip_blue: require('../assets/icons/geofence_trip_blue.png'),
  harsh_break_blue: require('../assets/icons/harsh_break_blue.png'),
  hourglass_grey: require('../assets/icons/hourglass_grey.png'),
  info_blue: require('../assets/icons/info_blue.png'),
  info_white: require('../assets/icons/info_white.png'),
  list_white: require('../assets/icons/list_white.png'),
  live_feed_blue: require('../assets/icons/live_feed_blue.png'),
  live_feed_white: require('../assets/icons/live_feed_white.png'),
  location_grey: require('../assets/icons/location_grey.png'),
  location_red: require('../assets/icons/location_red.png'),
  location_green: require('../assets/icons/location_green.png'),
  login_solid_blue: require('../assets/icons/login_solid_blue.png'),
  logout_white: require('../assets/icons/logout_white.png'),
  long_status_red: require('../assets/icons/long_status_red.png'),
  map_blue: require('../assets/icons/map_blue.png'),
  map_layer_blue: require('../assets/icons/map_layer_blue.png'),
  map_vehicle_blue: require('../assets/icons/map_vehicle_blue.png'),
  map_vehicle_green: require('../assets/icons/map_vehicle_green.png'),
  map_vehicle_grey: require('../assets/icons/map_vehicle_grey.png'),
  map_vehicle_orange: require('../assets/icons/map_vehicle_orange.png'),
  map_white: require('../assets/icons/map_white.png'),
  max_speed_grey: require('../assets/icons/max_speed_grey.png'),
  menu_solid_white: require('../assets/icons/menu_solid_white.png'),
  message_blue: require('../assets/icons/message_blue.png'),
  message_white: require('../assets/icons/message_white.png'),
  more_horizontal_white: require('../assets/icons/more_horizontal_white.png'),
  more_vertical_white: require('../assets/icons/more_vertical_white.png'),
  multi_select_blue: require('../assets/icons/multi_select_blue.png'),
  nosignal_blue: require('../assets/icons/nosignal_blue.png'),
  notification_white: require('../assets/icons/notification_white.png'),
  backArrow: require('../assets/icons/backArrow.png'),



  play_white: require('../assets/icons/play_white.png'),
  position_blue: require('../assets/icons/position_blue.png'),
  report_blue: require('../assets/icons/report_blue.png'),
  report_white: require('../assets/icons/report_white.png'),
  share_icon: require('../assets/icons/share_blue.png'),
  

  search_blue: require('../assets/icons/search_blue.png'),
  search_white: require('../assets/icons/search_white.png'),
  share_blue: require('../assets/icons/share_blue.png'),
  share_white: require('../assets/icons/share_white.png'),
  sort_white: require('../assets/icons/sort_white.png'),
  speed_blue: require('../assets/icons/speed_blue.png'),
  speed_circle_red: require('../assets/icons/speed_circle_red.png'),
  speed_limit: require('../assets/icons/speed_limit.png'),
  speed_red: require('../assets/icons/speed_red.png'),
  star_full_blue: require('../assets/icons/star_full_blue.png'),
  star_full_grey: require('../assets/icons/star_full_grey.png'),
  star_full_yellow: require('../assets/icons/star_full_yellow.png'),
  star_half_yellow: require('../assets/icons/star_half_yellow.png'),
  system_admin_white: require('../assets/icons/system_admin_white.png'),
  tick_blue: require('../assets/icons/tick_blue.png'),
  tick_white: require('../assets/icons/tick_white.png'),
  trash_blue: require('../assets/icons/trash_blue.png'),
  trip_blue: require('../assets/icons/trip_blue.png'),

  video_option_blue: require('../assets/icons/video_option_blue.png'),

  info_white_bg_blue: require('../assets/icons/info_white_bg_blue.png'),
  speed_max_grey: require('../assets/icons/speed_max_grey.png'),
  trip_start_end: require('../assets/icons/trip_start_end.png'),

  harsh_accelerate: require('../assets/icons/harsh_accelerate.png'),
  harsh_break: require('../assets/icons/harsh_break.png'),
  harsh_cornering: require('../assets/icons/harsh_cornering.png'),
  car_crash_red: require('../assets/icons/car_crash_red.png'),
  seat_belt_red: require('../assets/icons/seat_belt_red.png'),

  auto_alarm_white: require('../assets/icons/auto_alarm_white.png'),
  auto_report_white: require('../assets/icons/auto_report_white.png'),
  customization_white: require('../assets/icons/customization_white.png'),
  user_management_white: require('../assets/icons/user_management_white.png'),
  user_setting_white: require('../assets/icons/user_setting_white.png'),

  setting_blue: require('../assets/icons/setting_blue.png'),

  no_internet_grey: require('../assets/icons/no_internet_grey.png'),
};

export default Icons;
